image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u devtanna -p @EPngztg%5S0

build:
  stage: build
  script:
    - docker pull devtanna/foodable_front:v1.0 || true
    - docker build --cache-from devtanna/foodable_front:v1.0 -t devtanna/foodable_front:v1.0 -f docker/front/Dockerfile .
    - docker push devtanna/foodable_front:v1.0
#    - docker pull devtanna/foodable_back:v1.0 || true
#    - docker build --cache-from devtanna/foodable_back:v1.0 -t devtanna/foodable_back:v1.0 -f docker/back/Dockerfile .
#    - docker push devtanna/foodable_back:v1.0
#    - docker pull devtanna/foodable_scraper:v1.0 || true
#    - docker build --cache-from devtanna/foodable_scraper:v1.0 -t devtanna/foodable_scraper:v1.0 -f docker/scraper/Dockerfile .
#    - docker push devtanna/foodable_scraper:v1.0
  only:
    variables:
      - $CI_COMMIT_MESSAGE == /build images/
