image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u devtanna -p @EPngztg%5S0

build:
  stage: build
  script:
    - docker pull devtanna/foodable:v1.0 || true
    - docker build --cache-from devtanna/foodable:v1.0 -t devtanna/foodable:v1.0 -f docker/app/Dockerfile .
    - docker push devtanna/foodable:v1.0
  only:
    refs:
    - master
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[image-build\]/

