build:
  stage: build
  environment: Docker
  image: docker:stable
  before_script:
    - docker login -u devtanna -p $DOCKER_PASS
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker pull devtanna/foodable:v1.0 || true
    - docker build --cache-from devtanna/foodable:v1.0 -t devtanna/foodable:v1.0 -f docker/app/Dockerfile .
    - docker push devtanna/foodable:v1.0
  only:
    refs:
    - master
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[image-build\]/

deploy_azure_production:
  stage: deploy
  environment: Production
  image: trion/ng-cli-karma
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ##
    ## Optionally, if you will be using any Git commands, set the user name and
    ## and email.
    ##
    - git config --global user.email "dev.tanna@gmail.com"
    - git config --global user.name "Dev Tanna"
  only:
    refs:
    - master
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[azure-deploy\]/
  script:
    - echo $SSH_PRIVATE_KEY
    - echo $AZURE_IP
    - ssh -o StrictHostKeyChecking=no foodableae@$AZURE_IP 'cd ~/foodable && git checkout . && git clean -f -d && git reset HEAD && git pull origin master'
    - ssh -o StrictHostKeyChecking=no foodableae@$AZURE_IP 'cd ~/foodable && sudo npm install'
    - ssh -o StrictHostKeyChecking=no foodableae@$AZURE_IP 'cd ~/foodable && npm run build'
    - ssh -o StrictHostKeyChecking=no foodableae@$AZURE_IP 'cd ~/foodable && npm run stop-azure && npm run start-azure'
    - ssh -o StrictHostKeyChecking=no foodableae@$AZURE_IP 'sudo nginx -t'
    - ssh -o StrictHostKeyChecking=no foodableae@$AZURE_IP 'sudo systemctl restart nginx'
    - ssh -o StrictHostKeyChecking=no foodableae@$AZURE_IP 'sudo systemctl status nginx'
