build:
  stage: build
  environment: Docker
  image: docker:stable
  before_script:
    - docker login -u devtanna -p $DOCKER_PASS
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker pull devtanna/foodable:v1.0 || true
    - docker build --cache-from devtanna/foodable:v1.0 -t devtanna/foodable:v1.0 -f docker/app/Dockerfile .
    - docker push devtanna/foodable:v1.0
  only:
    refs:
    - master
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[image-build\]/

deploy_azure_production:
  stage: deploy
  environment: Production
  image: trion/ng-cli-karma
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
  cache:
    paths:
      - node_modules/
  only:
    refs:
    - master
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[azure-deploy\]/
  script:
    - sshpass -p $USER_PASS ssh foodableae@$AZURE_IP 'cd ~/foodable && git checkout . && git reset HEAD && git pull origin master'
    - sshpass -p $USER_PASS ssh foodableae@$AZURE_IP 'npm install'
    - sshpass -p $USER_PASS ssh foodableae@$AZURE_IP 'npm run build'
    - sshpass -p $USER_PASS ssh foodableae@$AZURE_IP 'npm run start-azure'
    - sshpass -p $USER_PASS ssh foodableae@$AZURE_IP 'sudo systemctl restart nginx'
    - sshpass -p $USER_PASS ssh foodableae@$AZURE_IP 'sudo systemctl status nginx'
