version: "3"
services:
  nginx-proxy:
    container_name: foodable_nginx
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - foodable
    links:
      - foodable
      - mongo

  foodable:
    container_name: foodable
    restart: always
    volumes:
      - .:/src
    command:  ["npm", "run", "dev"]
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - mongo
    links:
      - mongo

  scraper:
   container_name: foodable_scraper
   command: >
     sh -c "cron -f"
   restart: always
   volumes:
     - .:/app
     - /app/node_modules/
   build:
     context: .
     dockerfile: ./docker/scraper/Dockerfile
   environment:
     ENV: 'localhost'

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all", "--logpath=/tmp/mongod.log"]