version: "2"
services:
  foodable_front:
    container_name: foodable_front
    restart: always
    volumes:
      - .:/src
    command:  ["npm", "run", "dev"]
    environment:
      NODE_ENV: dev
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    ports:
      - "5000:5000"
    links:
      - foodable_back
  
  foodable_back:
    container_name: foodable_back
    restart: always
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile
    ports:
      - "4000:4000"
    links:
      - mongo
      - scraper
  
  scraper:
    container_name: scraper
    restart: always
    build:
      context: .
      dockerfile: ./docker/scraper/Dockerfile
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all", "--smallfiles", "--logpath=/tmp/mongod.log"]