version: "3"
services:
  myoffersapp:
    container_name: myoffersapp
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"