apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend-pod
spec:
  containers:
  - name: backend
    image: devtanna/foodable_back:v1.0
    imagePullPolicy: Always
    env:
    - name: ENABLE_K8
      value: true
    ports:
    - containerPort: 4000