apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db-pod
spec:
  containers:
  - name: mongo
    image: mongo
    imagePullPolicy: Never
    env:
    - name: MONGO_DATA_DIR
      value: /data/db
    command: ["mongod", "--bind_ip_all", "--smallfiles", "--logpath=/tmp/mongod.log"]
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongo-pv-claim
      mountPath: /data/db
  volumes:
  - name: mongo-pv-claim
    persistentVolumeClaim:
      claimName: mongo-pv-claim