apiVersion: v1
kind: Pod
metadata:
  name: foodable-pod
  labels:
    app: foodable-pod
spec:
  containers:
    - name: foodable
      image: devtanna/foodable:v1.0
      imagePullPolicy: Always
      env:
      - name: ENABLE_K8
        value: 'true'
      - name: NODE_ENV
        value: 'production'
      - name: MONGO_ENV
        value: 'atlas'
      ports:
        - containerPort: 4000
      command: ["npm","run","start"]
      livenessProbe:
        httpGet:
          path: /public/hc
          port: 4000
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /public/hc
          port: 4000
        initialDelaySeconds: 3
        periodSeconds: 3
